import { StyleSheet } from 'react-native';
import { colors } from '../../common';

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -12,
  },
  detailsCntainer: {
    position: 'absolute',
    top: 235,
    zIndex: 1,
    alignSelf: 'center',
  },
  innerShaodw: {
    backgroundColor: '#000000',
    width: 150,
    alignSelf: 'center',
    height: 10,
    position: 'absolute',
    zIndex: 1,
    opacity: 0.1,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 2,
    shadowOpacity: 1,
  },
  outerShadowStart: {
    backgroundColor: '#000000',
    width: 10,
    height: 26,
    position: 'absolute',
    zIndex: 1,
    opacity: 0.1,
    right: 0,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    bottom: 0,
    shadowColor: '#000000',
    shadowOffset: { width: 8, height: 0 },
    shadowRadius: 2,
    shadowOpacity: 1,
  },
  outerShadowEnd: {
    backgroundColor: '#000000',
    width: 10,
    height: 28,
    position: 'absolute',
    zIndex: 1,
    opacity: 0.1,
    left: 0,
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    bottom: 0,
    shadowColor: '#00000',
    shadowOffset: { width: -8, height: 0 },
    shadowRadius: 2,
    shadowOpacity: 1,
  },
  platContainer: {
    width: 153,
    height: 74,
    borderRadius: 10,
    backgroundColor: '#EDEDED',
    alignSelf: 'center',
    marginBottom: 3,
  },
  mainContainer: {
    backgroundColor: colors.platRed,
    flexDirection: 'row',
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    height: 34,
  },
  brandContainer: {
    flexDirection: 'row',
    borderTopEndRadius: 10,
    borderTopStartRadius: 10,
  },
  dot: {
    width: 12,
    height: 10,
    borderRadius: 6,
    backgroundColor: colors.white,
    zIndex: 5,
    marginTop: 6,
  },
  brandName: {
    marginTop: 3,
    fontSize: 18,
    color: '#646161',
    textShadowColor: colors.black,
    textShadowOffset: { width: 0, height: -2 },
    textShadowRadius: 0,
  },
  numberContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 42,
  },
  line: {
    height: 40,
    width: 7,
    backgroundColor: colors.white,
  },
  carNumber: {
    fontSize: 18,
    color: colors.black,
  },
  space_view: {
    height: 48,
  },
});

export default styles;
